pipeline{
    agent{
        docker{
            image 'mcr.microsoft.com/playwright:v1.26.0-focal'
            environment { 
                        MSYS_NO_PATHCONV=1
            }  
        }
    }
    stages{
        stage('install playwright'){
            steps{
            sh '''
            pwsh ./bin/Debug/net6.0/playwright.ps1 install
            dotnet build
            ''' 
            }
        }
    }
}