pipeline{
    agent{
        docker{
        docker () {
          MSYS_NO_PATHCONV=1 docker.exe
        }
        export -f docker
            image 'mcr.microsoft.com/playwright:v1.26.0-focal'
        }      
    }
    stages{
        stage('install playwright'){
            steps{
            sh '''
            pwsh ./bin/Debug/net6.0/playwright.ps1 install
            dotnet build
            ''' 
            }
        }
    }
}