pipeline{
    agent{
        docker{
            image 'mcr.microsoft.com/playwright/dotnet:v1.24.0-focal'
        }      
    }
    stages{
        stage('install playwright'){
            steps{
            sh '''
            pwsh ./bin/Debug/net6.0/playwright.ps1 install
            dotnet build
            ''' 
            }
        }
    }
}