pipeline{
    agent{
        docker{
            image 'mcr.microsoft.com/playwright/dotnet:v1.25.0-focal'
        }     
    }
    stages{
        stage('install playwright'){
            steps{
                dotnet build 
            }
        }
        stage('Tests Run'){
             steps{
              sh 'dotnet Test' 
            }
        }
    }
}